#!/bin/bash
# ============================================
# Threat Intel Orchestrator
# ============================================
# Monitors cybersecurity/AI news feeds
# and generates actionable intelligence
# ============================================

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
# shellcheck disable=SC2034
RED='\033[0;31m'
# shellcheck disable=SC2034
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
NC='\033[0m'

FEED_URL="https://raw.githubusercontent.com/DevCop95/cYHBernews/refs/heads/main/noticias.json"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FEED_DIR="$SCRIPT_DIR/feeds"
REPORT_DIR="$SCRIPT_DIR/reports"
DATA_DIR="$SCRIPT_DIR/threat-intel"

mkdir -p "$FEED_DIR" "$REPORT_DIR" "$DATA_DIR"

# ============================================
# FUNCTIONS
# ============================================

fetch_feed() {
    echo -e "${CYAN}[+] Fetching news feed...${NC}"
    curl -s "$FEED_URL" -o "$FEED_DIR/noticias.json"
    echo -e "${GREEN}[✓] Feed updated${NC}"
}

parse_cves() {
    echo -e "${CYAN}[+] Parsing CVEs...${NC}"
    cat "$FEED_DIR/noticias.json" | jq -r '
        [.[] | select(.iocs.cve != null and (.iocs.cve | length) > 0) | {
            id: .id,
            fecha: .fecha,
            severidad: .severidad,
            titulo: .titulo,
            cves: .iocs.cve,
            ttps: [.ttps[]?.name // empty],
            fuente: .fuente,
            enlace: .enlace_original
        }]
    ' > "$DATA_DIR/cves.json"
    
    COUNT=$(cat "$DATA_DIR/cves.json" | jq 'length')
    echo -e "${GREEN}[✓] $COUNT CVEs found${NC}"
}

parse_critical() {
    echo -e "${CYAN}[+] Filtering critical threats...${NC}"
    cat "$FEED_DIR/noticias.json" | jq -r '
        [.[] | select(.severidad == "CRITICA" or .severidad == "ALTA") | {
            id: .id,
            fecha: .fecha,
            severidad: .severidad,
            titulo: .titulo,
            categoria: .categoria,
            resumen: .resumen[0:200],
            ttps: [.ttps[]?.name // empty],
            cves: .iocs.cve // [],
            fuente: .fuente
        }]
    ' > "$DATA_DIR/critical.json"
    
    COUNT=$(cat "$DATA_DIR/critical.json" | jq 'length')
    echo -e "${GREEN}[✓] $COUNT critical/high threats${NC}"
}

parse_ttps() {
    echo -e "${CYAN}[+] Extracting TTPs (MITRE ATT&CK)...${NC}"
    cat "$FEED_DIR/noticias.json" | jq -r '
        [.[] | .ttps[]? | select(.id != null) | {
            id: .id,
            name: .name
        }] | unique_by(.id)
    ' > "$DATA_DIR/ttps.json"
    
    COUNT=$(cat "$DATA_DIR/ttps.json" | jq 'length')
    echo -e "${GREEN}[✓] $COUNT unique TTPs${NC}"
}

generate_threat_report() {
    echo -e "${CYAN}[+] Generating threat report...${NC}"
    
    DATE=$(date +%Y-%m-%d)
    REPORT_FILE="$REPORT_DIR/threat-intel-${DATE}.md"
    
    cat > "$REPORT_FILE" << 'HEADER'
# Threat Intelligence Report

**Automatically generated by Threat Intel Orchestrator**

---

## Executive Summary

HEADER
    
    # Contar estadísticas
    TOTAL=$(cat "$FEED_DIR/noticias.json" | jq 'length')
    CRITICA=$(cat "$FEED_DIR/noticias.json" | jq '[.[] | select(.severidad == "CRITICA")] | length')
    ALTA=$(cat "$FEED_DIR/noticias.json" | jq '[.[] | select(.severidad == "ALTA")] | length')
    MEDIA=$(cat "$FEED_DIR/noticias.json" | jq '[.[] | select(.severidad == "MEDIA")] | length')
    BAJA=$(cat "$FEED_DIR/noticias.json" | jq '[.[] | select(.severidad == "BAJA")] | length')
    
    cat >> "$REPORT_FILE" << EOF
| Severity | Count |
|-----------|----------|
| 🔴 CRITICAL | $CRITICA |
| 🟠 HIGH | $ALTA |
| 🟡 MEDIUM | $MEDIA |
| 🟢 LOW | $BAJA |
| **TOTAL** | **$TOTAL** |

---

## 🔴 Critical Vulnerabilities

EOF
    
    # Agregar CVEs críticos
    cat "$DATA_DIR/critical.json" | jq -r '
        .[] | select(.severidad == "CRITICA") |
        "### \(.titulo)\n\n- **Date:** \(.fecha)\n- **CVE:** \(.cves | join(", ") | if length > 0 then . else "N/A" end)\n- **TTPs:** \(.ttps | join(", ") | if length > 0 then . else "N/A" end)\n- **Source:** \(.fuente)\n\n\(.resumen)\n\n---\n"
    ' >> "$REPORT_FILE"
    
    cat >> "$REPORT_FILE" << 'SECTION'
## 🟠 High Severity Vulnerabilities

SECTION
    
    cat "$DATA_DIR/critical.json" | jq -r '
        .[] | select(.severidad == "ALTA") |
        "### \(.titulo)\n\n- **Date:** \(.fecha)\n- **CVE:** \(.cves | join(", ") | if length > 0 then . else "N/A" end)\n- **Source:** \(.fuente)\n\n\(.resumen)\n\n---\n"
    ' >> "$REPORT_FILE"
    
    cat >> "$REPORT_FILE" << 'SECTION'
## 📊 MITRE ATT&CK TTPs Detected

SECTION
    
    cat "$DATA_DIR/ttps.json" | jq -r '.[] | "- **\(.id)**: \(.name)"' >> "$REPORT_FILE"
    
    cat >> "$REPORT_FILE" << 'SECTION'

---

## 🛡️ Recommendations

### Immediate Actions
1. Review and apply patches for critical CVEs
2. Monitor IPs and IOC domains
3. Update WAF/IDS rules based on detected TTPs

### Continuous Monitoring
1. Run `./threat-intel-monitor.sh` every hour
2. Review daily reports in `reports/`
3. Update attack vectors in the registry

---

*Automatically generated report*
SECTION
    
    echo -e "${GREEN}[✓] Report generated: $REPORT_FILE${NC}"
}

generate_ioc_list() {
    echo -e "${CYAN}[+] Generating IOC list...${NC}"
    
    DATE=$(date +%Y-%m-%d)
    IOC_FILE="$DATA_DIR/iocs-${DATE}.txt"
    
    cat "$FEED_DIR/noticias.json" | jq -r '
        [.[] | 
            (.iocs.cve // [])[]?,
            (.iocs.domain // [])[]?,
            (.iocs.url // [])[]
        ] | unique | .[]
    ' > "$IOC_FILE" 2>/dev/null || echo "" > "$IOC_FILE"
    
    COUNT=$(wc -l < "$IOC_FILE")
    echo -e "${GREEN}[✓] $COUNT IOCs exported to $IOC_FILE${NC}"
}

show_summary() {
    echo ""
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${MAGENTA}  THREAT INTELLIGENCE SUMMARY${NC}"
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    
    echo -e "${CYAN}Critical CVEs:${NC}"
    cat "$DATA_DIR/cves.json" | jq -r '.[] | select(.severidad == "CRITICA") | "  🔴 \(.titulo) - \(.cves | join(", "))"' 2>/dev/null | head -10
    echo ""
    
    echo -e "${CYAN}High-Level Threats:${NC}"
    cat "$DATA_DIR/critical.json" | jq -r '.[] | "  \(.severidad | if . == "CRITICA" then "🔴" else "🟠" end) \(.titulo)"' 2>/dev/null | head -10
    echo ""
    
    echo -e "${CYAN}Most Common TTPs:${NC}"
    cat "$DATA_DIR/ttps.json" | jq -r '.[0:5][] | "  • \(.id): \(.name)"' 2>/dev/null
    echo ""
}

# ============================================
# MAIN
# ============================================

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           THREAT INTEL ORCHESTRATOR v1.0                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

case "${1:-full}" in
    fetch)
        fetch_feed
        ;;
    parse)
        parse_cves
        parse_critical
        parse_ttps
        ;;
    report)
        generate_threat_report
        generate_ioc_list
        ;;
    summary)
        show_summary
        ;;
    full)
        fetch_feed
        parse_cves
        parse_critical
        parse_ttps
        generate_threat_report
        generate_ioc_list
        show_summary
        ;;
    *)
        echo "Usage: $0 [fetch|parse|report|summary|full]"
        ;;
esac

echo ""
echo -e "${GREEN}[✓] Process completed${NC}"
